# MySQL. Versions 5.1.10 and up are supported.

default: &default
  adapter: mysql2
  username: user
  password: password
  prefix: wp_
  host: ip
  port: port

development:
  <<: *default
  database: gaceta

test:
  <<: *default
  database: wp_test
  prefix: wp_

production:
  <<: *default
  database: wp_production